### ISSUE TITLE
Make a release

### ISSUE THREAD

**Issue by anjandev** [bahamas10/zzz-user-hooks#4]
Hi!

I found these scripts very useful and would like to document and package them for voidlinux. See:

https://github.com/void-linux/void-docs/issues/377#issuecomment-653778048

Before I can package these scripts, there needs to be a release. Please issue a release when you get the chance.

Thank you!

**Comment by bahamas10** [comment]
Created!  https://github.com/bahamas10/zzz-user-hooks/releases/tag/v1.0.0

I also added a LICENSE and CHANGELOG file... thanks!
