### ISSUE TITLE
change from sudo to runuser or chpst

### ISSUE THREAD

**Issue by anjandev** [bahamas10/zzz-user-hooks#5]
chpst is already used in void's runit scripts and this would lower the dependencies for this script.

Please let me know if you would accept a PR with this change.

**Comment by bahamas10** [comment]
thanks for taking this on! I had tried to change this over to use `chpst` instead of `sudo` in the past but remember I had hit a couple of issues.

I'll take a look at this again today - I would prefer to drop the dep on `sudo` and just use `chpst` personally.

**Comment by bahamas10** [comment]
updated in `v1.1.0`!

I swapped out sudo for chpst, and also made it so the script would be executed with the PWD of the users home directory.

**Comment by anjandev** [comment]
@bahamas10  please tag v1.1.0

**Comment by bahamas10** [comment]
@anjandev done! sorry about that
